title: Low-Light Image Enhancement
description: Perosnal implementation of X. Fu, D. Zeng, Y. Huang, X.-P. Zhang, and X. Ding, “A weighted variational model for simultaneous reflectance and illumination estimation,” in Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR), 2016, pp. 2782–2790.

theme: just-the-docs

url: https://LoucOoc.github.io

aux_links:
  Template Repository: https://github.com/LoucOoc/Retinex_variational_model
aux_links_new_tab: true

nav_enabled: true

heading_anchors: true

color_scheme: light   # "light" 或 "dark"

mermaid:
  version: "9.1.3"

callouts:
  highlight:
    title: Motivation
    color: yellow